/* eslint-disable react-hooks/exhaustive-deps */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

// import React, { useEffect, useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
// import IslandScene from '../assets/3d/island.glb';
// // eslint-disable-next-line no-unused-vars
// import { a } from '@react-spring/three';
// import { useFrame , useThree } from '@react-three/fiber';

// const Island = ({isRotating , setIsRotating , setCurrentStage, ...props}) => {
//     const IslandRef = useRef();
  

//     const {gl , viewport} = useThree();
//   const { nodes, materials } = useGLTF(IslandScene);
  
//   const lastX = useRef(0)
//   const rotatingSpeed = useRef(0)
//   const dampingFactor = 0.95;

//   const handlePointerDown =  (e) => {
//     e.stopPropagation();
//     e.preventDefault();
//     setIsRotating(true);

//     const clientX = e.touches ? e.touches[0].clientX : e.clientX

//     lastX.current = clientX;
//   }

  
//   const handlePointerUp =  (e) => {
//     e.stopPropagation();
//     e.preventDefault();
//     setIsRotating(false);

//   }

  
//   const handlePointerMove =  (e) => {
//     e.stopPropagation();
//     e.preventDefault();

//     if (isRotating) {
//       const clientX = e.touches ? e.touches[0].clientX : e.clientX

//       const delta = (clientX - lastX.current) / viewport.width;
  
//       IslandRef.current.rotation.y += delta * 0.01 * Math.PI;
  
//       lastX.current = clientX;
//       rotatingSpeed.current = delta * 0.01 * Math.PI; 
//     }
    
//   }

//   const handleKeyDown = (e) => {
//     if (e.key === 'ArrowLeft') {
//       if(!isRotating) setIsRotating(true);
//       IslandRef.current.rotation.y +=  0.01 * Math.PI;
//     } else if (e.key === 'ArrowRight'){
//       if(!isRotating) setIsRotating(true);
//       IslandRef.current.rotation.y -=  0.01 * Math.PI;
//     }
//   }

//   const handleKeyUp = (e) => {
//     if(e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
//       setIsRotating(false);
//     }
//   }

//   useFrame(() => {
//     if (!isRotating) {
//       rotatingSpeed.current *= dampingFactor;

//       if(Math.abs(rotatingSpeed.current) < 0.001){
//         rotatingSpeed.current = 0;
//       }

//       IslandRef.current.rotation.y += rotatingSpeed.current;
//     } else{
     
//       const rotation = IslandRef.current.rotation.y;
  
//     const normalizedRotation =  ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);
//     console.log("Rotation:", normalizedRotation.toFixed(2));


//       // Set the current stage based on the island's orientation
//       switch (true) {
//         case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
//           setCurrentStage(4);
//           break;
//         case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
//           setCurrentStage(3);
//           break;
//         case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
//           setCurrentStage(2);
//           break;
//         case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
//           setCurrentStage(1);
//           break;
//         default:
//           setCurrentStage(null);
//       }
//     }
//   })

//   useEffect(() => {
//     const canvas = gl.domElement
//   canvas.addEventListener('pointerdown', handlePointerDown);
//   canvas.addEventListener('pointerup', handlePointerUp);
//   canvas.addEventListener('pointermove', handlePointerMove);
//   document.addEventListener('keydown', handleKeyDown);
//   document.addEventListener('keyup', handleKeyUp);

//   return () => {
//     canvas.removeEventListener('pointerdown', handlePointerDown);
//     canvas.removeEventListener('pointerup', handlePointerUp);
//     canvas.removeEventListener('pointermove', handlePointerMove);
//     document.removeEventListener('keydown', handleKeyDown);
//     document.removeEventListener('keyup', handleKeyUp);
//   }
//   }, [gl, handlePointerDown, handlePointerUp, handlePointerMove])

//   // useFrame(() => {
//   //   if (IslandRef.current) {
//   //     IslandRef.current.rotation.y += 0.011; // Rotate model slowly
//   //   }
//   // });

  
//   return (
    
//     <a.group ref={IslandRef} scale={0.5} position={[0, -1, 0]} {...props} >
//       <mesh
//         geometry={nodes.polySurface944_tree_body_0.geometry}
//         material={materials.PaletteMaterial001}
//       />
//       <mesh
//         geometry={nodes.polySurface945_tree1_0.geometry}
//         material={materials.PaletteMaterial001}
//       />
//       <mesh
//         geometry={nodes.polySurface946_tree2_0.geometry}
//         material={materials.PaletteMaterial001}
//       />
//       <mesh
//         geometry={nodes.polySurface947_tree1_0.geometry}
//         material={materials.PaletteMaterial001}
//       />
//       <mesh
//         geometry={nodes.polySurface948_tree_body_0.geometry}
//         material={materials.PaletteMaterial001}
//       />
//       <mesh
//         geometry={nodes.polySurface949_tree_body_0.geometry}
//         material={materials.PaletteMaterial001}
//       />
//       <mesh
//         geometry={nodes.pCube11_rocks1_0.geometry}
//         material={materials.PaletteMaterial001}
//       />
//     </a.group>
    
//   )
  
// }

// useGLTF.preload('/assets/3d/island.glb');




// export default Island


//   SAME CODE WITH SOME DEBUGGING......

import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import IslandScene from '../assets/3d/island.glb';
import { a } from '@react-spring/three';
import { useFrame, useThree } from '@react-three/fiber';

const Island = ({
  isRotating,
  setIsRotating,
  setCurrentStage,
  currentStage,
  ...props
}) => {
  const IslandRef = useRef();
  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(IslandScene);

  const lastX = useRef(0);
  const rotatingSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  };

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  };

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current) / viewport.width;

      IslandRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
      rotatingSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'ArrowLeft') {
      if (!isRotating) setIsRotating(true);
      IslandRef.current.rotation.y += 0.01 * Math.PI;
      rotatingSpeed.current = 0.0125;
    } else if (e.key === 'ArrowRight') {
      if (!isRotating) setIsRotating(true);
      IslandRef.current.rotation.y -= 0.01 * Math.PI;
      rotatingSpeed.current = -0.0125;
    }
  };

  const handleKeyUp = (e) => {
    if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
      setIsRotating(false);
    }
  };

  useFrame(() => {
    if (!IslandRef.current) return;

    // Apply damping when not rotating
    if (!isRotating) {
      rotatingSpeed.current *= dampingFactor;
      if (Math.abs(rotatingSpeed.current) < 0.001) {
        rotatingSpeed.current = 0;
      }
      IslandRef.current.rotation.y += rotatingSpeed.current;
    }

    const currentYRotation = IslandRef.current.rotation.y;
    const normalizedRotation =
      ((currentYRotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

    // Debug rotation
    console.log('Rotation:', normalizedRotation.toFixed(2));

    let newStage = currentStage;

    switch (true) {
      case normalizedRotation >= 5.0 && normalizedRotation <= 6.2:
        newStage = 4;
        break;
      case normalizedRotation >= 0.5 && normalizedRotation <= 1.6:
        newStage = 3;
        break;
      case normalizedRotation >= 2.0 && normalizedRotation <= 3.0:
        newStage = 2;
        break;
      case normalizedRotation >= 4.0 && normalizedRotation <= 5.0:
        newStage = 1;
        break;
      default:
        break;
    }

    if (newStage !== currentStage) {
      console.log('🌀 New Stage:', newStage);
      setCurrentStage(newStage);
    }
  });

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener('pointerdown', handlePointerDown);
    canvas.addEventListener('pointerup', handlePointerUp);
    canvas.addEventListener('pointermove', handlePointerMove);
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp);

    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown);
      canvas.removeEventListener('pointerup', handlePointerUp);
      canvas.removeEventListener('pointermove', handlePointerMove);
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp);
    };
  }, [gl,handlePointerDown,handlePointerMove,handlePointerUp]);

  return (
    <a.group ref={IslandRef} scale={0.5} position={[0, -1, 0]} {...props}>
      <mesh
        geometry={nodes.polySurface944_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface945_tree1_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface946_tree2_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface947_tree1_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface948_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface949_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.pCube11_rocks1_0.geometry}
        material={materials.PaletteMaterial001}
      />
    </a.group>
  );
};

useGLTF.preload('/assets/3d/island.glb');

export default Island;
